name: Smoke Test Cardano Rosetta
description: Runs the image, waits, then performs a basic smoke test
inputs:
  tag:
    description: Docker tag
    required: false
    default: latest
  network-identifier:
    description: Supported Cardano network
    required: false
    default: mainnet
runs:
  using: composite
  steps:
    - name: Run
      run: docker run -d -p 8080:8080 --name cardano-rosetta cardano-rosetta:${{ inputs.tag }}
      shell: bash
    - name: Test
      run: |
        sleep 10
        curl -X POST -H "Content-Type: application/json" -d '{"network_identifier":{"blockchain": "cardano", "network":"${{ inputs.network-identifier }}"}}' http://localhost:8080/network/status
        docker rm -f cardano-rosetta
      shell: bash
