name: Post-release

on:
  release:
    types:
      - published

jobs:
  build-and-push-release-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build Cardano Rosetta
        uses: ./.github/actions/build_cardano_rosetta
        with:
          cardano-rosetta-version: ${{ github.event.release.tag_name }}
      - name: Smoke test Cardano Rosetta image
        uses: ./.github/actions/smoke_test_cardano_rosetta
        with:
          cardano-rosetta-version: ${{ github.event.release.tag_name }}
      - name: Apply latest tag
        run: |
          docker tag cardano-rosetta:${{ github.event.release.tag_name }} inputoutput/cardano-rosetta:${{ github.event.release.tag_name }}
          docker tag cardano-rosetta:${{ github.event.release.tag_name }} inputoutput/cardano-rosetta:latest
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push to Docker Hub
        run: |
          docker push inputoutput/cardano-rosetta:${{ github.event.release.tag_name }}
          docker push inputoutput/cardano-rosetta:latest
